spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    web:
      resources:
        static-locations: classpath:/static/
  security:
    csrf:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


